//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportScheduleInWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place_type_relation
    {
        public int ptr_id { get; set; }
        public int ptr_place_id { get; set; }
        public int ptr_place_type_id { get; set; }
    
        public virtual Place_types Place_types { get; set; }
        public virtual Places Places { get; set; }
    }
}
