//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportScheduleInWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registered
    {
        public System.Guid reg_guid { get; set; }
        public string reg_login { get; set; }
        public string reg_password { get; set; }
        public string reg_surname { get; set; }
        public string reg_name { get; set; }
        public string reg_patronymic { get; set; }
        public string reg_email { get; set; }
    }
}
