//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportScheduleInWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_permissions
    {
        public int rp_id { get; set; }
        public int rp_role_id { get; set; }
        public int rp_permission_id { get; set; }
    
        public virtual Permissions Permissions { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
