//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportScheduleInWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wish_user_relation
    {
        public int wur_id { get; set; }
        public int wur_wish_id { get; set; }
        public int wur_user_id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Wishes Wishes { get; set; }
    }
}
