//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportScheduleInForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wishes()
        {
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int wish_id { get; set; }
        public System.DateTime wish_createdate { get; set; }
        public System.DateTime wish_deadline { get; set; }
        public Nullable<int> wish_total_attempts { get; set; }
        public string wish_report_type_name { get; set; }
        public string wish_report_type_xml { get; set; }
        public string wish_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
